# Generated by Django 3.2.5 on 2021-10-27 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profile', '0005_profile_friends'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='Profile/Posts')),
                ('video', models.FileField(blank=True, null=True, upload_to='Profile/Video')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_posts', to='Profile.profile')),
                ('like', models.ManyToManyField(blank=True, null=True, related_name='like', to='Profile.Profile')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
