# Generated by Django 3.2.5 on 2022-01-07 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liked',
            name='value',
        ),
    ]
