# Generated by Django 3.2.5 on 2022-01-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0006_alter_profile_friends'),
        ('Post', '0004_remove_liked_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liked',
            name='user',
        ),
        migrations.AddField(
            model_name='liked',
            name='user',
            field=models.ManyToManyField(to='Profile.Profile'),
        ),
    ]
