# Generated by Django 3.2.5 on 2022-02-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0015_postgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postgroup',
            name='group_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
