# Generated by Django 3.2.5 on 2022-03-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0006_alter_profile_friends'),
        ('Post', '0017_auto_20220303_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='postgroup',
            name='likegp',
            field=models.ManyToManyField(blank=True, related_name='likegp', to='Profile.Profile'),
        ),
    ]
