# Generated by Django 3.2.5 on 2022-04-30 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0009_alter_message_options'),
        ('Post', '0027_rewards'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewards',
            name='reward_earner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reward_earner', to='Profile.profile'),
        ),
    ]
