# Generated by Django 3.2.5 on 2021-10-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_profile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='background',
            field=models.ImageField(default='cover4.jpg', upload_to='Profile_background'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='main_photo',
            field=models.ImageField(default='cover2.jpg', upload_to='Profile_main'),
        ),
    ]
