# Generated by Django 3.2.5 on 2021-10-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_auto_20211026_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='background',
            field=models.ImageField(blank=True, default='cover4.jpg', null=True, upload_to='Profile_background'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='main_photo',
            field=models.ImageField(blank=True, default='cover2.jpg', null=True, upload_to='Profile_main'),
        ),
    ]
