# Generated by Django 3.2.5 on 2022-01-20 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0006_alter_profile_friends'),
        ('Post', '0005_auto_20220114_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liked',
            name='user',
        ),
        migrations.AddField(
            model_name='liked',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_liked', to='Profile.profile'),
        ),
    ]
