# Generated by Django 3.2.5 on 2022-01-25 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0006_alter_profile_friends'),
        ('Post', '0006_auto_20220120_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Programming', 'Programming'), ('Sports', 'Sports'), ('Entertainment', 'Entertainment'), ('Health', 'Health'), ('Fitness', 'Fitness'), ('Meditation', 'Meditation'), ('Music', 'Music')], max_length=200)),
                ('members', models.ManyToManyField(blank=True, null=True, to='Profile.Profile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='Profile.profile')),
            ],
        ),
    ]
