# Generated by Django 3.2.5 on 2022-01-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0006_alter_profile_friends'),
        ('Post', '0007_joingroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='joingroup',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joingroup',
            name='members',
            field=models.ManyToManyField(blank=True, to='Profile.Profile'),
        ),
    ]
