# Generated by Django 3.2.5 on 2022-03-03 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0006_alter_profile_friends'),
        ('Post', '0016_alter_postgroup_group_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postgroup',
            options={'ordering': ('-created',)},
        ),
        migrations.CreateModel(
            name='LikedGroupPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('postgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grouppost_liked', to='Post.postgroup')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_likedgrouppost', to='Profile.profile')),
            ],
        ),
    ]
