# Generated by Django 3.2.5 on 2022-03-09 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0007_relationship'),
        ('Post', '0019_commentonpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentOnGroupPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_gpost', to='Post.postgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commnet_guser_profile', to='Profile.profile')),
            ],
        ),
    ]
