# Generated by Django 3.2.5 on 2022-03-10 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0020_commentongrouppost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentongrouppost',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='commentonpost',
            options={'ordering': ('-created',)},
        ),
    ]
