# Generated by Django 3.2.5 on 2022-04-14 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0022_rewards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewards',
            name='group_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_post_r', to='Post.postgroup'),
        ),
    ]
