# Generated by Django 3.2.5 on 2022-04-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0023_alter_rewards_group_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewards',
            name='reward',
            field=models.CharField(choices=[('pawn', 10), ('rook', 35), ('bishop', 30), ('knight', 20), ('queen', 80), ('king', 100)], max_length=200),
        ),
    ]
