# Generated by Django 3.2.5 on 2022-04-15 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0024_alter_rewards_reward'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rewards',
        ),
    ]
