# Generated by Django 3.2.5 on 2022-04-30 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0029_alter_rewards_reward_earner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rewards',
            name='reward_earner',
        ),
    ]
